package:
  name: clickhouse-24
  version: 24.4.1.2088
  epoch: 1
  description: ClickHouse is the fastest and most resource efficient open-source database for real-time apps and analytics.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - clickhouse=${{package.full-version}}

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-17-dev
      - cmake
      - coreutils
      - findutils
      - git
      - grep
      - llvm-libcxx-17-dev
      - llvm-lld-17-dev
      - nasm
      - ninja
      - perl
      - python3
      - rust
      - yasm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ClickHouse/ClickHouse
      tag: v${{package.version}}-stable
      expected-commit: 7fb8f96d3da26cbcd42aa967a9f06b8a780de351

  # The default build script is defensive and tries to protect against defining cflags.
  - uses: patch
    with:
      patches: allow_cflags.patch

  - runs: git submodule update --init

  - uses: cmake/configure
    with:
      opts: |
        -DCOMPILER_CACHE=disabled \
        -DNO_ARMV81_OR_HIGHER=1

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "${{package.name}}-dev"
    description: "headers for clickhouse"
    pipeline:
      - uses: split/dev

  - name: "${{package.name}}-bash-completion"
    description: "bash completion for clickhouse"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/bash-completion/completions
          mv ${{targets.destdir}}/usr/share/bash-completion/completions/clickhouse ${{targets.subpkgdir}}/usr/share/bash-completion/completions

  - name: "${{package.name}}-compat"
    description: "docker compat for clickhouse"
    pipeline:
      - runs: |
          cd build
          install -Dm755 ../docker/server/entrypoint.sh ${{targets.subpkgdir}}/entrypoint.sh
          mkdir -p ${{targets.subpkgdir}}/etc/clickhouse-server/config.d/
          cp  ../docker/server/docker_related_config.xml ${{targets.subpkgdir}}/etc/clickhouse-server/config.d/docker_related_config.xml

update:
  # Ignoring LTS versions
  ignore-regex-patterns:
    - '.*lts$'
  github:
    identifier: ClickHouse/ClickHouse
    strip-prefix: v
    strip-suffix: -stable
