package:
  name: croc
  version: 9.6.17
  epoch: 1
  description: Easily and securely send things from one computer to another
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/schollz/croc
      expected-commit: f6d862eac0e004422c431030b9bd1e405666fe56
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/schollz/croc/v9@v9.6.16

  - uses: go/build
    with:
      packages: .
      output: croc
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: schollz/croc
    strip-prefix: v
