# This package is required for the metric-collector-for-apache-cassandra.
# There are bunch of plugins are disabled to trim down the size of the final package and to avoid unnecessary dependencies.
# But in case you need a collectd package with a plugin we already disabled we could do that by separating the collectd into subpackages
# for each package that uses collectd. For example, if you need the collectd package with the write_riemann plugin enabled, you could
# create a subpackage for it and enable the plugin in the subpackage. The subpackage will be built and installed alongside the main package.
package:
  name: datastax-collectd
  version: 0.1.7
  epoch: 0
  description: "The system statistics collection daemon."
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - curl-dev
      - eudev-dev
      - flex
      - gdk-pixbuf-dev
      - gpsd-dev
      - harfbuzz-dev
      - hiredis-dev
      - i2c-tools-dev
      - iptables-dev
      - jansson-dev
      - libatasmart-dev
      - libdbi-dev
      - libgcrypt-dev
      - libmemcached-dev
      - libmicrohttpd-dev
      - libmnl-dev
      - libmodbus-dev
      - libnotify-dev
      - liboping-dev
      - libpcap-dev
      - libpq-16
      - librdkafka-dev
      - libtool
      - libxml2-dev
      - lm-sensors-dev
      - mosquitto-dev
      - net-snmp-dev
      - openipmi-dev
      - openjdk-17-default-jdk
      - openldap-dev
      - openssl-dev>3
      - owfs-dev
      - pango-dev
      - patchelf
      - perl-dev
      - pkgconf
      - pkgconf-dev
      - postgresql-16-dev
      - rabbitmq-c
      - rabbitmq-c-dev
      - riemann-c-client-dev
      - rrdtool-dev
      - varnish
      - yajl-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 64f01e378864d90fb889567cdd638b594185fe28
      repository: https://github.com/datastax/collectd.git
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: disable-scribe.patch

  - runs: |
      # Copy source for MCAC
      mkdir -p /tmp/collectd
      cp -rf . /tmp/collectd/

      ./clean.sh
      ./build.sh

      CFLAGS="-Wno-error=stringop-overflow \
        -Wno-error=unused-variable \
        -Wno-error=unused-function \
        -Wno-error=cpp \
        -Wno-error=stringop-truncation \
        -Wno-error=format-truncation \
        -Wno-error=deprecated-declarations \
        -Wno-error=incompatible-pointer-types \
        -Wno-error=dangling-pointer= \
        -fPIC"
      CPPFLAGS="$CFLAGS" \
      CXXFLAGS="$CFLAGS"
      ./configure \
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc/collectd \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --localstate=/var \
        --with-data-max-name-len=1024 \
        --enable-all-plugins \
        --disable-turbostat \
        --disable-virt \
        --disable-xencpu \
        --disable-debug \
        --disable-ascent \
        --disable-rrdcached \
        --disable-lvm \
        --disable-write_kafka \
        --disable-curl_xml \
        --disable-dpdkstat \
        --disable-dpdkevents \
        --disable-gmond \
        --disable-grpc \
        --disable-gps \
        --disable-ipmi \
        --disable-lua \
        --disable-mqtt \
        --disable-modbus \
        --disable-mysql \
        --disable-intel_pmu \
        --disable-intel_rdt \
        --disable-static \
        --disable-write_riemann \
        --disable-zone \
        --disable-apple_sensors \
        --disable-lpar \
        --disable-tape \
        --disable-aquaero \
        --disable-mic \
        --disable-netapp \
        --disable-notify_email \
        --disable-nut \
        --disable-onewire \
        --disable-oracle \
        --disable-pf \
        --disable-python \
        --disable-redis \
        --disable-write_redis \
        --disable-routeros \
        --disable-rrdtool \
        --disable-write_scribe \
        --disable-sensors \
        --disable-sigrok \
        --disable-write_mongodb \
        --disable-xmms \
        --disable-write_sensu \
        --disable-zfs-arc \
        --disable-tokyotyrant \
        --disable-write_kafka \
        --disable-barometer \
        --with-perl-bindings="INSTALLDIRS=vendor INSTALL_BASE=" \
        --without-libaquaero5 \
        --without-libstatgrab \
        --without-libupsclient \
        --without-included-ltdl \
        --without-libgrpc++ \
        --without-libgps \
        --without-libmodbus \
        --without-libpython \
        --without-libsensors \
        --without-mic

      make
      make DESTDIR="${{targets.destdir}}" install
      find "${{targets.destdir}}" \( -name perllocal.pod -o -name .packlist \) -delete

      mkdir -p "${{targets.destdir}}"/etc/collectd.d
      mkdir -p "${{targets.destdir}}"/etc/init.d
      mkdir -p "${{targets.destdir}}"/usr/include/collectd/core
      mkdir -p "${{targets.destdir}}"/usr/include/collectd/liboconfig

      install -D -m755 ./collectd.initd "${{targets.destdir}}"/etc/init.d/collectd

      # Install all header files to allow building out-of-tree plugins.
      # This is based on Debian.
      for path in $(find src -path src/libcollectdclient -prune \
        -o -path src/liboconfig -prune \
        -o -name '*.h' -print)
      do
        install -D -m644 "$path" "${{targets.destdir}}"/usr/include/collectd/core/${path#src/}
      done

      install -D -m644 ./src/liboconfig/oconfig.h -t "${{targets.destdir}}"/usr/include/collectd/liboconfig/
      cd "${{targets.destdir}}"/usr/include/collectd/
      # Update include path for collectd core header files.
      headers=$(find ./core ./liboconfig -type f -name '*.h')
      for path in $headers; do
        sed -r -i "s|(include\s+)\".*\<${path##*/}\"|\1\"collectd/${path#./}\"|" $headers
      done

  - uses: strip

subpackages:
  - name: ${{package.name}}-mcac
    description: Provides collectd source code for MCAC
    dependencies:
      runtime:
        - datastax-collectd
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/opt/metrics-collector/lib/collectd
          cp -rf /tmp/collectd/* "${{targets.contextdir}}"/opt/metrics-collector/lib/collectd/

update:
  enabled: true
  github:
    identifier: datastax/collectd
    strip-prefix: v
    use-tag: true
