package:
  name: gdbm
  version: 1.23
  epoch: 7
  description: "GNU dbm is a set of database routines which use extensible hashing"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - gettext-dev
      - libtool
      - rsync
      - texinfo

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.savannah.gnu.org/gdbm.git
      tag: v${{package.version}}
      expected-commit: 6de35853113a2a4a8eab661c569fe0d9171eb13a

  - runs: |
      ./bootstrap

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "gdbm-dev"
    description: "gdbm headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - gdbm

update:
  enabled: true
  release-monitor:
    identifier: 882
