package:
  name: libassuan
  version: 3.0.0
  epoch: 0
  description: IPC library used by some GnuPG related software
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libgpg-error-dev
      - libtool
      - texinfo

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.gnupg.org/libassuan.git
      tag: libassuan-${{package.version}}
      expected-commit: 0351ecfa4f35ad44684075abec153574986b11bd

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --enable-maintainer-mode

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libassuan-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libassuan
    description: libassuan dev

  - name: libassuan-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    description: libassuan manpages

update:
  enabled: true
  release-monitor:
    identifier: 1559
