package:
  name: libseccomp
  version: 2.5.5
  epoch: 5
  description: interface to the Linux Kernel's syscall filtering mechanism
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cython
      - gcc
      - gperf
      - libtool
      - linux-headers
      - pkgconf-dev
      - python3
      - python3-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/seccomp/libseccomp.git
      tag: v${{package.version}}
      expected-commit: f0b04ab0b4fc0bc2cde6da1f407b4a487fe6d78f

  - runs: |
      ./autogen.sh
      cp ./src/arch-gperf-generate . && chmod +x ./arch-gperf-generate

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libseccomp-static
    pipeline:
      - uses: split/static
    description: libseccomp static

  - name: libseccomp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libseccomp
        - linux-headers
    description: libseccomp dev

  - name: libseccomp-doc
    pipeline:
      - uses: split/manpages
    description: libseccomp manpages

update:
  enabled: true
  github:
    identifier: seccomp/libseccomp
    strip-prefix: v
