package:
  name: libunistring
  version: "1.2"
  epoch: 3
  description: Library for manipulating Unicode strings and C strings
  copyright:
    - license: GPL-2.0-or-later OR LGPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - glibc-iconv
      - posix-libc-utils

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.savannah.gnu.org/git/libunistring.git
      tag: v${{package.version}}
      expected-commit: 479b580dedca32662b34336183abfec95b71c42e

  - runs: ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --localstatedir=/var \

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libunistring-static
    pipeline:
      - uses: split/static
    description: libunistring static

  - name: libunistring-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libunistring
        - glibc-iconv
    description: libunistring dev

update:
  enabled: true
  release-monitor:
    identifier: 1747
