package:
  name: lttng-ust
  version: 2.13.8
  epoch: 2
  description: LTTng 2.0 Userspace Tracer
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - asciidoc
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - libxml2-utils
      - linux-headers
      - pkgconf-dev
      - py3-setuptools
      - python3
      - userspace-rcu-dev
      - util-linux-dev
      - xmlto

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.lttng.org/lttng-ust.git
      tag: v${{package.version}}
      expected-commit: 5a8c530cec95b827a4840c0d032b502f82f0dde3

  - runs: ./bootstrap

  - uses: autoconf/configure
    with:
      opts: |
        --disable-static \
        --disable-numa \
        --enable-python-agent

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      # Change the shebang in /usr/bin to python3 instead of python
      sed -i 's|python|python3|g' ${{targets.destdir}}/usr/bin/lttng-gen-tp

  - uses: strip

subpackages:
  - name: lttng-ust-doc
    pipeline:
      - uses: split/manpages
    description: lttng-ust manpages

  - name: lttng-ust-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - lttng-ust
        - userspace-rcu-dev
    description: lttng-ust dev

  - name: lttng-ust-tools
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv "${{targets.destdir}}"/usr/bin "${{targets.subpkgdir}}"/usr/
    description: lttng-ust tools

  - name: py3-lttng
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/python* "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/lib/liblttng-ust-python* "${{targets.subpkgdir}}"/usr/lib/
    description: lttng-ust python agent

update:
  enabled: true
  release-monitor:
    identifier: 7135
