package:
  name: make
  version: 4.4.1
  epoch: 4
  description: "GNU make"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.savannah.gnu.org/git/make.git
      tag: ${{package.version}}
      expected-commit: d66a65ad5a0e31b287f53930b0f09e31801f1613

  - runs: ./autogen.sh

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share \
         --without-guile

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  manual: true # be careful upgrading Make as it is a core package
  release-monitor:
    identifier: 1877
