package:
  name: neuvector-db
  version: 2024.07.23
  epoch: 0
  description: NeuVector vulnerability database for the SUSE NeuVector Container Security Platform
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - crane

pipeline:
  - runs: |
      # Fetch NeuVector scanner
      crane export neuvector/scanner:latest scanner.tar

      # Extract image
      mkdir -p scanner
      tar xvf scanner.tar -C scanner

      # Install DB
      mkdir -p ${{targets.contextdir}}/etc/neuvector/db
      cp scanner/etc/neuvector/db/cvedb ${{targets.contextdir}}/etc/neuvector/db/cvedb

  - uses: strip

test:
  pipeline:
    - runs: |
        if [[ -f "/etc/neuvector/db/cvedb" ]]; then
          echo "CVE DB found!" && exit 0
        else
          echo "CVE DB not found!" && exit 1
        fi

# We need to regularly pull the CVE DB to pick up updates.
# Use the timed releases repository to trigger daily updates.
update:
  enabled: true
  github:
    identifier: EyeCantCU/timed-releases
    strip-prefix: daily/
    tag-filter: daily/
    use-tag: true
