package:
  name: opensearch-security-2
  version: 2.11.1.0
  epoch: 0
  description: Secure your cluster with TLS, numerous authentication backends
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - apk-tools
      - build-base
      - busybox
      - ca-certificates-bundle
      - gradle
      - wolfi-base
      - openjdk-17-default-jvm
      - unzip
    
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/opensearch-project/security.git
      tag: ${{package.version}}
      expected-commit: 2dab119387212d5047062100f799934b7ffbffea

  - runs: |
      # ./gradlew clean assemble
      echo "org.gradle.daemon=false" >> gradle.properties
      ./gradlew clean assemble --parallel -Dbuild.snapshot="false" -Dbuild.version_qualifier=""

      mkdir -p "${{targets.destdir}}/usr/share/opensearch/plugins/opensearch-security"
      mv build/distributions/opensearch-security-${{package.version}}.jar "${{targets.destdir}}/usr/share/opensearch/plugins/opensearch-security/"
      #mv build/distributions/opensearch-security* "${{targets.destdir}}/usr/share/opensearch/plugins/opensearch-security/"
      unzip build/distributions/opensearch-security-${{package.version}}.zip -d "${{targets.destdir}}/usr/share/opensearch/plugins/opensearch-security"

  - uses: strip

update:
  enabled: true
  github:
    identifier: opensearch-project/security
    tag-filter: 2.
