package:
  name: opentelemetry-collector
  version: 0.104.0
  epoch: 2
  description: OpenTelemetry Collector
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - curl
      - go

pipeline:
  - runs: |
      set -x

      # Use the build config from the official otel-core release
      # https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol/manifest.yaml
      # The manifest is updated as part of the release process and so should match the
      # lastest version released from open-telemetry/opentelemetry-collector
      curl -o builder-config.yaml https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-releases/main/distributions/otelcol/manifest.yaml

  - uses: git-checkout
    with:
      repository: https://github.com/open-telemetry/opentelemetry-collector
      tag: v${{package.version}}
      expected-commit: a082f2e439e8f77a9a9503d54d8afea576f2d08c

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./cmd/mdatagen

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./cmd/otelcorecol

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./receiver

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./exporter

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./extension

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./processor

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./connector

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./extension/zpagesextension

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./config/configgrpc

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./component

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./otelcol

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./pdata

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./consumer

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./service

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./extension/auth

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./extension/ballastextension

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./extension/memorylimiterextension

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./config/configauth

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./config/confighttp

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./processor/memorylimiterprocessor

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./processor/batchprocessor

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./otelcol/otelcoltest

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./pdata/pprofile

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./receiver/otlpreceiver

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./receiver/nopreceiver

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./connector/forwardconnector

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./exporter/loggingexporter

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./exporter/otlphttpexporter

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./exporter/otlpexporter

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./exporter/debugexporter

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./exporter/nopexporter

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./internal/e2e

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1
      modroot: ./pdata/testdata

  - uses: go/build
    with:
      packages: .
      modroot: ./cmd/builder
      output: ocb

  - runs: |
      set -x
      # Use the builder to compile opentelemetry-collector
      ${{targets.destdir}}/usr/bin/ocb --config=builder-config.yaml

      install -Dm755 ./_build/otelcol "${{targets.destdir}}"/usr/bin/otelcol
      rm -f ${{targets.destdir}}/usr/bin/ocb

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: Compatability package to place binary in the location expected by upstream helm chart
    pipeline:
      - runs: |
          # The helm chart expects the binary to be /otelcol instead of /usr/bin/otelcol
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/otelcorecol ${{targets.subpkgdir}}/otelcol

update:
  enabled: true
  github:
    identifier: open-telemetry/opentelemetry-collector
    strip-prefix: v
    use-tag: true
    tag-filter: v
