package:
  name: openssf-compiler-options
  version: 20240627
  epoch: 0
  description: "Compiler Options Hardening Guide for C and C++"
  url: https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.html
  copyright:
    - license: CC-BY-4.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"
      cp -r etc usr "${{targets.destdir}}"
      for i in $(seq 15 18); do
        ln -s clang "${{targets.destdir}}"/etc/clang-$i
      done

test:
  environment:
    contents:
      packages:
        - clang-18
        - clang-18-dev
        - gcc
        - glibc-dev
        - hardening-check
  pipeline:
    - name: hardening check
      runs: |
        cat >hello.c <<"EOF"
        #include <alloca.h>
        #include <stdio.h>
        #include <string.h>
        int main(int argc, char* argv[]) {
            printf("hello-c");
            char buffer[5000];
            strcpy(buffer, argv[0]);
            char* dynbuffer = alloca(argc * 1000);
            strcpy(dynbuffer, argv[0]);
            return buffer[argc] + dynbuffer[argc];
        }
        EOF
        clang-18 -v -o hello-clang hello.c
        out=$(./hello-clang 1 || true)
        [ "$out" = "hello-c" ]

        gcc -v -o hello-gcc hello.c
        out=$(./hello-gcc 1 || true)
        [ "$out" = "hello-c" ]

        hardening-check hello-clang
        hardening-check hello-gcc

update:
  enabled: false
