package:
  name: perl-http-cookies
  version: "6.11"
<<<<<<< Updated upstream
  epoch: 0
=======
  epoch: 2
>>>>>>> Stashed changes
  description: HTTP cookie jars
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl-http-date
      - perl-http-message

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-http-date
      - perl-http-message

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libwww-perl/HTTP-Cookies.git
      tag: v${{package.version}}
      expected-commit: a2766f4548385a281d6d40a420d31431947b5f41

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-http-cookies-doc
    pipeline:
      - uses: split/manpages
    description: perl-http-cookies manpages

update:
  enabled: true
  github:
    identifier: libwww-perl/HTTP-Cookies
    use-tag: true
    strip-prefix: v
