package:
  name: perl-file-listing
  version: "6.16"
<<<<<<< Updated upstream
  epoch: 1
=======
  epoch: 3
>>>>>>> Stashed changes
  description: Parse directory listing
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl-http-date

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-http-date

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/PerlAlien/File-Listing.git
      tag: v${{package.version}}
      expected-commit: d098e126670ab44d6da4dd6ae66b7d121754d0f0

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-file-listing-doc
    pipeline:
      - uses: split/manpages
    description: perl-file-listing manpages

update:
  enabled: true
  github:
    identifier: PerlAlien/File-Listing
    use-tag: true
    strip-prefix: v
