package:
  name: pgbouncer
  version: 1.22.1
  epoch: 2
  description: lightweight connection pooler for PostgreSQL
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - libevent-dev
      - libtool
      - openssl-dev
      - pkgconf-dev

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      expected-commit: de1e9cb75324a624d18fc3dd5d714d12a8da0db6
      repository: https://github.com/pgbouncer/pgbouncer.git
      tag: pgbouncer_${{vars.mangled-package-version}}

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/pgbouncer/
      install -Dm755 ./etc/pgbouncer.ini "${{targets.contextdir}}"/etc/pgbouncer/
      install -Dm755 ./etc/userlist.txt "${{targets.contextdir}}"/etc/pgbouncer/

  - uses: strip

subpackages:
  - name: pgbouncer-doc
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/doc/
          mv "${{targets.destdir}}"/usr/share/doc/pgbouncer "${{targets.subpkgdir}}"/usr/share/doc
    description: pgbouncer manpages

update:
  # Doesn't work with var transforms
  enabled: false
  manual: true
  github:
    identifier: pgbouncer/pgbouncer
    strip-prefix: pgbouncer_
    tag-filter: pgbouncer_
