package:
  name: popt
  version: 1.19
  epoch: 2
  description: commandline option parser
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 916e61045d268f7e37ade5ec047eb77e8299e6ad
      repository: https://github.com/rpm-software-management/popt.git
      tag: popt-${{package.version}}-release

  - uses: autoconf/configure
    with:
      opts: |
        --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

subpackages:
  - name: popt-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - popt
    description: popt dev

  - name: popt-lang
    pipeline:
      - uses: split/locales
    description: popt locales

  - name: popt-doc
    pipeline:
      - uses: split/manpages
    description: popt manpages

update:
  enabled: true
  version-transform:
    - match: popt-(\d+)\.(\d+)-release
      replace: $1.$2
  github:
    identifier: rpm-software-management/popt
    strip-prefix: v
