package:
  name: pulumi-language-java
  version: "1.12.0"
  epoch: 1
  description: Pulumi Language SDK for Java
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a94b7dacf70eb832de0f1e727b47e881d435ed3e
      repository: https://github.com/pulumi/pulumi-java.git
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: |-
        github.com/cloudflare/circl@v1.6.1
      modroot: tests

  - uses: go/bump
    with:
      deps: |-
        github.com/cloudflare/circl@v1.6.1
      modroot: sdk/java/pulumi/src/test/resources/testproj

  - uses: go/bump
    with:
      deps: |-
        github.com/cloudflare/circl@v1.6.1
      modroot: pkg

  - uses: go/build
    with:
      ldflags: -X github.com/pulumi/pulumi-java/pkg/version.Version=v${{package.version}}
      modroot: pkg
      output: pulumi-language-java
      packages: ./cmd/pulumi-language-java

update:
  enabled: true
  git:
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        pulumi-language-java --help
