package:
  name: puppeteer-core
  version: 22.6.3
  epoch: 0
  description: "Node.js API for Chrome"
  copyright:
    - license: Apache-2.0
  options:
    # The Puppeteer BareOS module incorperates libraries for aarch64
    # so we enable no-depends to avoid aarch64 libs from being marked
    # as a dependency on amd64
    no-depends: true
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    packages:
      - build-base
      - busybox
      - nodejs
      - npm

pipeline:
  - name: npm install
    runs: |
      npm install -g ${{package.name}}@${{package.version}} -prefix ${{targets.destdir}}/usr

test:
  environment:
    environment:
      NODE_PATH: "/usr/lib/node_modules"
  pipeline:
    - runs: |
        node -e "console.log(require.resolve('puppeteer-core'))"

update:
  enabled: true
  github:
    identifier: puppeteer/puppeteer
    use-tag: true
    strip-prefix: puppeteer-core-v
    tag-filter: puppeteer-core
