package:
  name: socat
  version: 1.8.0.0
  epoch: 2
  description: Multipurpose relay for binary protocols
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers
      - openssl-dev
      - readline-dev
      - libtool
      - intltool
      - gettext-dev
      - libpipeline

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2da070164d454971d5c970b5278e645051f0d0f7
      repository: https://repo.or.cz/socat.git
      tag: tag-${{package.version}}

  - uses: patch
    with:
      patches: netdb-internal.patch use-linux-headers.patch

  - runs: autoreconf -fiv

  - uses: autoconf/configure

  - runs: |
      make
      make DESTDIR="${{targets.destdir}}" install

  - uses: strip

subpackages:
  - name: socat-doc
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/socat
          install -m644 EXAMPLES doc/*.html doc/*.css "${{targets.subpkgdir}}"/usr/share/socat

update:
  enabled: true
  release-monitor:
    identifier: 4848
