package:
  name: sudo-rs
  version: 0.2.1
  epoch: 1
  description: A memory safe implementation of sudo and su.
  copyright:
    - license: MIT
  checks:
    disabled:
      - setuidgid
  dependencies:
    runtime:
      - linux-pam-dev

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-pam-dev
      - openssl-dev
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/memorysafety/sudo-rs
      tag: v${{package.version}}
      expected-commit: 195d6f851904ab00357f040eef35e31abaebbe1b

  - runs: |
      cargo build --release
      mkdir -p ${{targets.destdir}}/usr/bin
      mv target/release/sudo ${{targets.destdir}}/usr/bin/
      mv target/release/su ${{targets.destdir}}/usr/bin/

      # However, this binary must have the setuid flag set and must be owned by the root user in order to provide any useful functionality.
      chmod u+s  ${{targets.destdir}}/usr/bin/sudo
      chmod u+s  ${{targets.destdir}}/usr/bin/su

  - uses: strip

update:
  enabled: true
  github:
    identifier: memorysafety/sudo-rs
    strip-prefix: v
