package:
  name: volume-modifier-for-k8s
  version: 0.2.0
  epoch: 1
  description: volume-modifier-for-k8s is a sidecar deployed alongside CSI drivers to enable volume modification through annotations on the PVC.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0a7adf05fc48053f322c38bf36fdbe276d835131
      repository: https://github.com/awslabs/volume-modifier-for-k8s
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0
      modroot: .

  - uses: go/build
    with:
      ldflags: -X main.version=${{package.version}}
      modroot: .
      output: volume-modifier-for-k8s
      packages: ./cmd

  - uses: strip

update:
  enabled: true
  github:
    identifier: awslabs/volume-modifier-for-k8s
    strip-prefix: v
    tag-filter: v
