package:
  name: xz
  version: 5.6.1
  epoch: 0
  description: "Library and CLI tools for XZ and LZMA compressed files"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - uses: fetch # use fetch instead of git-checkout else there is a circular dependency with git
    with:
      uri: https://storage.googleapis.com/us.artifacts.mattmoor-chainguard.appspot.com/xz.tgz
      expected-sha256: a84685382551df5bdc438936980db7dbbddbed2a10f8a31bdd61d67434b47d69
      strip-components: 0

  - runs: |
      ls -lA

      autoreconf -fiv

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}} \
        --prefix=/usr \
        --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "xz-dev"
    description: "xz headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - xz

  - name: "xz-doc"
    description: "xz documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: false
  github:
    identifier: tukaani-project/xz
    strip-prefix: v
